---
volumePermissions:
  enabled: false
  securityContext:
    runAsUser: auto

primary:
  podSecurityContext:
    enabled: true
  containerSecurityContext:
    enabled: false

shmVolume:
  chmod:
    enabled: false

auth:
  database: mediator
  username: mediator
  password: mediator
  postgresPassword: mediator
