apiVersion: v1
data:
  ACAPY_WALLET_KEY: {{ .Values.config.acapywalletkey }}
  MEDIATOR_AGENT_ADMIN_API_KEY: {{ .Values.config.mediatoragentadminapikey }}
  MEDIATOR_CONTROLLER_ADMIN_API_KEY: {{ .Values.config.mediatorcontrolleradminapikey }}
kind: Secret
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque