apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 3000
    port: 3000
  - name: wss
    targetPort: 3001
    port: 3001
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}

